name: Lint
on: [push]
jobs:
  Lint-With-PhpCS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run lint
        uses: nick-zh/composer@php7.4
        run: make lint
